language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 홈
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
  - chmod +x gradlew

script: "./gradlew clean build"

before_deploy:
  - mkdir -p before-deploy # zip에 포함시킬 파일들을 담을 디렉토리 생성
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy * # before-deploy로 이동 후 전체 압축
  - cd ../ && mkdir -p deploy # 상위 디렉토리로 이동 후 deploy 디렉토리 생성
  - mv before-deploy/before-deploy.zip deploy/alone00.zip # deploy로 zip 파일 이동

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # TRAVIS repo setting 설정 값
    secret_access_key: $AWS_SECRET_KEY # TRAVIS repo setting 설정 값
    bucket: alone00
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # TRAVIS repo setting 설정 값
    secret_access_key: $AWS_SECRET_KEY # TRAVIS repo setting 설정 값

    bucket: alone00
    key: alone00.zip
    bundle_type: zip
    application: alone00
    deployment_group: alone00-group

    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - workforksg@gmail.com