language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 홈
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
  - chmod +x gradlew

script: "./gradlew clean build"

before_deploy:
  - zip -r alone00 *
  - mkdir -p deploy
  - mv alone00.zip deploy/alone00.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # TRAVIS repo setting 설정 값
    secret_access_key: $AWS_SECRET_KEY # TRAVIS repo setting 설정 값
    bucket: alone00
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - workforksg@gmail.com